name: Build and Deploy to GitHub Pages

on:
    push:
        branches:
            - main
    
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
    deploy:
        name: Deploy
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        env:
          VITE_TMDB_TOKEN: ${{ secrets.VITE_TMDB_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                node-version: lts/*
                cache: 'npm'

            - name: Install dependencies
              run: npm ci
              # uses: bahmutov/npm-install@v1

            - name: Validate
              run: |
                  npm run lint:check
                  npm run format:check

            - name: Build
              run: npm run build
              env:
                VITE_TMDB_TOKEN: ${{ secrets.VITE_TMDB_TOKEN }}

            - name: Setup Pages
              uses: actions/configure-pages@v4

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                # Upload static build folder
                path: './docs' # ./dist

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
            # - name: Deploy to GitHub Pages
            #   run: |
            #     git config --global user.email "mbborromeo@@gmail.com"
            #     git config --global user.name "Michael Borromeo"
            #     npm run deploy
